version: '3'
services:
 node:
  image: node
  tty: true
  ports:
   - 80:80
  depends_on:
   - mongo
  volumes:
   - ./node/app:/var/www/app

 mongo:
  image: mongo
  ports: 
   - 33060:3306
  environment:
   MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  volumes: 
   - ./mongo/store:/data/db

 mongo-express:
  image: mongo-express
  ports:
   - 8081:8081
  environment:
   ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_ADMINUSERNAME}
   ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_ADMINPASSWORD}

 react:
  image: node
  tty: true
  ports:
   - 3306:80
  volumes: 
   - ./client/app:/var/www/client